version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=https://nginx-docker-xhl3.onrender.com
    restart: always
