services:
  - type: web
    name: nginx-server
    env: docker
    repo: https://github.com/PetrJoe/nginx-docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: API_URL
        value: https://api.yourdomain.com
    healthCheckPath: /
    healthCheckTimeout: 5s
